module.exports = {
  towns: getTowns()
};

function getTowns(){
  return [
    { 'town': 'Abu Hail' },
    { 'town': 'Al Aweer' },
    { 'town': 'Al Barsha' },
    { 'town': 'Al Garhoud' },
    { 'town': 'Al Hamriya' },
    { 'town': 'Al Karama' },
    { 'town': 'Al Mamzar' },
    { 'town': 'Al Muntasa' },
    { 'town': 'Al Muraqqabat' },
    { 'town': 'Al Quoz' },
    { 'town': 'Al Qusais' },
    { 'town': 'Al Rashidiya' },
    { 'town': 'Al Rigga' },
    { 'town': 'Al Satwa' },
    { 'town': 'Al Shindagha' },
    { 'town': 'Al Sufouh' },
    { 'town': 'Al Wasl' },
    { 'town': 'Corniche Deira' },
    { 'town': 'Dubai Investment Park' },
    { 'town': 'Dubai Marina' },
    { 'town': 'Emirates Hills' },
    { 'town': 'Jebel Ali' },
    { 'town': 'Jumeira' },
    { 'town': 'Jumeira Palm' },
    { 'town': 'Jumeirah 1' },
    { 'town': 'Jumeirah Garden City' },
    { 'town': 'Jumeirah Lake Towers' },
    { 'town': 'Jumeirah Palm' },
    { 'town': 'Madinat Jumeirah' },
    { 'town': 'Mankhool' },
    { 'town': 'Mirdiff' },
    { 'town': 'Nad Al Hamar' },
    { 'town': 'Nad Al Sheba' },
    { 'town': 'Naif Square' },
    { 'town': 'Oud Metha' },
    { 'town': 'Port Saeed' },
    { 'town': 'Ranches' },
    { 'town': 'Ras Al Khor' },
    { 'town': 'Sheikh Zayed Road' },
    { 'town': 'Trade Center' },
    { 'town': 'Umm Al Sheif' },
    { 'town': 'Umm Hurair' },
    { 'town': 'Umm Ramool' },
    { 'town': 'Umm Suqeim' },
    { 'town': 'Zabeel' },
    { 'town': 'Other' }
  ];
}
